### ISSUE TITLE
Comentarios Entrega 0

### ISSUE THREAD

**Issue by edjus** [Algo3Tp2GrupoT15/Algoritmos-3-FIUBA-TP2#1]
Buenas, les dejo un par de comentarios:

- [x] Actualizar la integración continua y cobertura, siguen apuntando al proyecto base.
- [x] Eliminar la clase `Message` si no es parte del modelo.
- [x] La clase `Pregunta` no se usa, ver si es necesaria , podría ser una interfaz o clase abstracta.
- [x] Respecto a la prueba1 `UnaPreguntadeVerdaderoFalsoPuedeCrearseIndicandoCualEsLaRespuestaCorrectaTest`, me parece que la idea es que dado una pregunta con su respuesta correcta vos le pases otra respuesta y te diga si es correcta o no. Como está ahora no sé ve mucho la utilidad del mensaje `escorrecta()` de `Pregunta`.
- La idea sería usar el mensaje anterior para determinar el puntaje de los jugadores.
Ejem:
Tengo una pregunta con 2 opciones: a, b, (correcta es a), entonces el jugador 1 responde a y el jugador 2 responde b (ellos no saben cual es la correcta). Ambos envian su respuesta a la pregunta y la pregunta sabe cual es la correcta (usando el mensaje del item anterior) y asigna el puntaje si corresponde.

**Comment by JulioCastillo1** [comment]
Buenas Edson, tenemos una nueva versión de la entrega en el branch entrega1-versión2. Ahora agregamos la integración con travis, por lo que debería estar activa si se configuró bien, mañana la probamos editando algo del código.
